import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Giorgio',
      email: 'giorgio@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Giota',
      email: 'giota@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  enoikiastes: [
    {
      name: '1os enoikiastis',
      slug: '1os-enoikiastis',
      territory: 'dasos',
      tel: '697895689',
      image: '/enikiastis_avatar.png',
      age: 35,
      children: {
        boys: 0,
        girls: 1,
        firstBoysAge: 0,
        secondBoysAge: 0,
        firstGirlsAge: 14,
        secondGirlsAge: 0,
      },
      animals: { cat: 1, dog: 0, other: null },
      rating: 4.5,
      numReviews: 8,
      description: 'καλός ενοικιαστής',
    },
    {
      name: '2os enoikiastis',
      slug: '2os-enoikiastis',
      territory: 'dasos1',
      tel: '697895689',
      image: '/enikiastis_avatar.png',
      age: 25,
      children: {
        boys: 1,
        girls: 0,
        firstBoysAge: 12,
        secondBoysAge: 0,
        firstGirlsAge: 0,
        secondGirlsAge: 0,
      },
      animals: {},
      rating: 3.5,
      numReviews: 8,
      description: 'ανήσυχος ενοικιαστής',
    },
    {
      name: '3os enoikiastis',
      slug: '3os-enoikiastis',
      territory: 'dasos2',
      tel: '697895689',
      image: '/enikiastis_avatar.png',
      age: 55,
      children: {
        boys: 1,
        girls: 1,
        firstBoysAge: 12,
        secondBoysAge: 0,
        firstGirlsAge: 10,
        secondGirlsAge: 0,
      },
      animals: { cat: 1, dog: 2, other: null },
      rating: 4.0,
      numReviews: 4,
      description: 'βρομιάρης ενοικιαστής',
    },
    {
      name: '4os enoikiastis',
      slug: '4os-enoikiastis',
      territory: 'dasos3',
      image: '/enikiastis_avatar.png',
      age: 75,
      children: {
        boys: 2,
        girls: 1,
        firstBoysAge: 12,
        secondBoysAge: 4,
        firstGirlsAge: 17,
        secondGirlsAge: 0,
      },
      tel: '697895689',
      animals: {
        dog: 0,
        cat: 3,
        other: null,
      },
      rating: 2.5,
      numReviews: 8,
      description: 'υπερβολικά φιλόζωος ενοικιαστής',
    },
    {
      name: '5os enoikiastis',
      slug: '5os-enoikiastis',
      territory: 'dasos4',
      tel: '697895689',
      image: '/enikiastis_avatar.png',
      age: 55,
      children: {
        boys: 0,
        girls: 2,
        firstBoysAge: 0,
        secondBoysAge: 0,
        firstGirlsAge: 3,
        secondGirlsAge: 7,
      },
      animals: { cat: 0, dog: 0, other: `κορκοδειλος` },
      rating: 3.5,
      numReviews: 8,
      description: 'χαμός ενοικιαστής',
    },
    {
      name: '6os enoikiastis',
      slug: '6os-enoikiastis',
      territory: 'dasos5',
      tel: '697895689',
      image: '/enikiastis_avatar.png',
      age: 65,
      children: 'χωρίς παιδιά',
      animals: 0,
      rating: 3.0,
      numReviews: 4,
      description: 'βαρετός ενοικιαστής',
    },
  ],
};
export default data;
